---
title: "Replicación 1"
author: "Eduardo Clark"
date: "5 de octubre de 2018"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
require(readstata13)
require(dplyr)
require(purrr)
require(texreg)
require(broom)

```

# 1 Replicación

## (1) Congresos. La base original contiene información sobre cuatro Congresos estadounidenses (105to-108vo,de1997-2004). Sin embargo,cada modelo se centra en los legisladores de un solo Congreso. Comienza creando 4 bases distintas,una para cada Congreso.  

## (2) Estadísticas descriptivas


## (4) Tabla 3 (versión libre). En la Tabla 3, la autora examina en qué medida los resultados varían por género o aliación partidaria. Para eso, corrió cuatro versiones de cada modelo incluido en la Tabla 2: el primero para el subconjunto de legisladores hombres, el segundo para el subconjunto de legisladoras mujeres, el tercero para los demócratas, y el cuarto para los republicanos.

* **(a) La información sobre el sexo del primer hijo de un subconjunto de 227 legisladores del
108vo Congreso se encuentra en el archivo genold108.dta. Debes averiguar cómo usar
la función merge() para unir estos datos con los legisladores del 108vo Congreso en la
base original.**


    - AQUI VA LA TABLA

    - El coeficiente de ngirl representa como cambia el score NOW o AAUW cuando el legislador tiene una hija adicional. Es decir que si el legislador tiene por ejemplo dos hijas mujeres, el score sube 2 * 2.65 en el caso de NOW para la 105 legislatura.

    - Podemos calcular el efecto del número de hijas mujeres al sumar los coeficientes de ngirls y de ngirls:female y multiplicarlos por el número de hijas mujeres. Por ejemplo en el caso de AAUW para la 105 legislatura seria (2.53 -1.27) * el número de hijas.

    - Los resultados son consistentes con Washington, en el sentido qeu tener hijas impact mas a los legisladores hombres en terminos de su mejora de *score* legislativo NOW o AAUW.

* **(b) Repite el ejercicio anterior pero con la aliación partidaria de los legisladores. ¿Qué indica
el coefciente de ngirls? ¿Cómo puedes calcular el efecto del número de hijas mujeres
entre los legisladores republicanos? ¿Encuentras diferencias sustantivas respecto a
los resultados reportados por Washington?**

     - AQUI VA LA TABLA

     - El coeficiente de ngirl representa como cambia el score NOW o AAUW cuando el legislador tiene una hija adicional.
        
    - El efecto de número de hijas mujeres en repúblicos se obtiene de multiplicar el coeficiente de ngirls por el número de hijas. Aqui no entra el factor interacción ya que la variable interacción aplica para cuando el legislador es democrata.
        
     - Se respeta la misma dirección del texto de Washington, a los repúblicanos les crea un mayor cambio (en terminos de su score NOW y/o AAUW) el tener una hija o una hija adicional.

* (a) Haz una versión más simple de la segunda y tercera columnas de la Tabla 3, incluyendo una interacción entre ngirls y female. ¿Qué indica el coeciente de  ngirls? ¿Cómo puedes calcular el efecto del número de hijas mujeres entre las legisladoras mujeres? ¿Qué tanto dieren tus resultados de los reportados por Washington?

## (5) Crédito extra: Tabla A1. Replica la Tabla 1 del apéndice, que muestra que (para los miembros del 108o Congreso), el sexo del primer hijo determina el número de hijas mujeres, pero no el número total de hijos:

* **(a) La información sobre el sexo del primer hijo de un subconjunto de 227 legisladores del
108vo Congreso se encuentra en el archivo genold108.dta. Debes averiguar cómo usar
la función merge() para unir estos datos con los legisladores del 108vo Congreso en la
base original.**

    - Evidencia en Tables.R
    
* **(b) Replica exactamente los resultados de la Tabla A1.**
    
    - AQUI VA LA TABLA
    
* **(c) Repite el ejercicio pero quitando los controles, i.e. incluyendo únicamente la variable
First child female como predictor. ¿Observas algún cambio sustantivo?**

    - AQUI VA LA TABLA
    
    - Hay un cambio del doble en el número de hijos para el congreso en general, pero es muy pequeño el coeficiente. En general se observa practicamente lo mismo

# Afirmaciones

